//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotovExam2022
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Books
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> CountInStore { get; set; }
        public Nullable<int> CountInStock { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }


        [NotMapped]
        public string TitleFull
        {
            get => "Название: " + Title;
        }

        [NotMapped]
        public string GenreFull
        {
            get => "Жанр: " + Genre;
        }

        [NotMapped]
        public string AuthorFull
        {
            get => "Автор: " + Author;
        }

        [NotMapped]
        public string CostFull
        {
            get => "Цена: " + Cost.ToString();
        }

        [NotMapped]
        public string CountInStoreFull
        {
            get => "Количество в магазине: " + CountInStore;
        }

        [NotMapped]
        public string CountInStockFull
        {
            get => "Количество на складе: " + CountInStock;
        }

        [NotMapped]
        public int FullCount
        {
            get => (int)CountInStock + (int)CountInStore;
        }

        [NotMapped]
        public string DescriptionFull
        {
            get => "Описание: " + Description;
        }

        [NotMapped]
        public string Image
        {
            get => "\\" + Cover;
        }
    }
}
