//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotovExam2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> OrderGetDate { get; set; }
        public Nullable<int> BooksCount { get; set; }
        public Nullable<double> OrderCostSale { get; set; }
        public Nullable<int> OrderSale { get; set; }
    }
}
